version: '3.8'
services:
  server:
    image: eraysahin06/car-meets-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  client:
    image: eraysahin06/car-meets-client
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
